name: Build and Deploy puconvocation-com to Cloud Run

on:
  push:
    tags:
      - "puconvocation-com-v*"

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GAR_LOCATION: ${{ secrets.ARTIFACT_REGISTRY_LOCATION }}
  SERVICE: ${{ secrets.PUCONVOCATION_COM_CLOUD_RUN_NAME }}
  REGION: ${{ secrets.PUCONVOCATION_COM_CLOUD_RUN_LOCATION }}

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      # Authenticate Docker to Google Cloud Artifact Registry
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

      - name: 'Write Env File'
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: ${{ github.workspace }}/frontend/websites/puconvocation-com/.env.local
          FILE_BASE64: ${{ secrets.PUCONVOCATION_COM_ENV }}

      - name: 'Write JWKS File'
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: ${{ github.workspace }}/frontend/websites/puconvocation-com/public/.well-known/jwks.json
          FILE_BASE64: ${{ secrets.PUCONVOCATION_COM_JWKS }}

      - name: Build and Push Container
        working-directory: ./frontend/websites/puconvocation-com
        run: |-
          docker build  -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/production/${{ env.SERVICE }}:${{ github.sha }}" ./
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/production/${{ env.SERVICE }}:${{ github.sha }}"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/production/${{ env.SERVICE }}:${{ github.sha }}
          flags: '--port 3000'
